//! Standalone Rust generator (`hvm gen-rs`).
//!
//! Emits one `rustc`-compilable file: the HVM runtime, compiled `interact_call`
//! (same fast paths as `gen-c`), and a `main`. Existing `.hvm` books are unchanged.

use crate::cmp;
use crate::hvm;

const HVM_RS: &str = include_str!("hvm.rs");
const READBACK_RS: &str = include_str!("standalone_readback.rs");

const COMPILED_HOOK: &str = "tm.interact_call(net, a, b, book)";
const COMPILED_HOOK_NEW: &str = "interact_call_compiled(net, tm, a, b)";

const WRAPPERS: &str = r#"
#[inline(always)] fn get_tag(p: Port) -> Tag { p.get_tag() }
#[inline(always)] fn get_val(p: Port) -> Val { p.get_val() }
#[inline(always)] fn new_port(tag: Tag, val: Val) -> Port { Port::new(tag, val) }
#[inline(always)] fn new_pair(a: Port, b: Port) -> Pair { Pair::new(a, b) }
#[inline(always)] fn get_fst(p: Pair) -> Port { p.get_fst() }
#[inline(always)] fn get_snd(p: Pair) -> Port { p.get_snd() }
#[inline(always)] fn node_load(net: &GNet, i: u32) -> Pair { net.node_load(i as usize) }
#[inline(always)] fn node_take(net: &GNet, i: u32) -> Pair { net.node_take(i as usize) }
#[inline(always)] fn node_store(net: &GNet, i: u32, val: Pair) { net.node_store(i as usize, val) }
#[inline(always)] fn node_create(net: &GNet, i: u32, val: Pair) { net.node_create(i as usize, val) }
#[inline(always)] fn vars_create(net: &GNet, i: u32, val: Port) { net.vars_create(i as usize, val) }
#[inline(always)] fn vars_take(net: &GNet, i: u32) -> Port { net.vars_take(i as usize) }
#[inline(always)] fn enter(net: &GNet, p: Port) -> Port { net.enter(p) }
#[inline(always)] fn link(net: &GNet, tm: &mut TMem, a: Port, b: Port) { tm.link(net, a, b) }
#[inline(always)] fn interact_eras(net: &GNet, tm: &mut TMem, a: Port, b: Port) -> bool { tm.interact_eras(net, a, b) }
#[inline(always)] fn node_alloc_1(net: &GNet, tm: &mut TMem, lps: &mut u32) -> u32 { tm.node_alloc_1(net, lps) as u32 }
#[inline(always)] fn vars_alloc_1(net: &GNet, tm: &mut TMem, lps: &mut u32) -> u32 { tm.vars_alloc_1(net, lps) as u32 }
#[inline(always)] fn new_u24(v: u32) -> Val { Numb::new_u24(v).0 }
#[inline(always)] fn get_u24(v: Val) -> u32 { Numb(v).get_u24() }
#[inline(always)] fn operate(a: Val, b: Val) -> Val { Numb::operate(Numb(a), Numb(b)).0 }
"#;

pub fn generate_rs(book: &hvm::Book) -> String {
  let mut runtime = HVM_RS.replace(COMPILED_HOOK, COMPILED_HOOK_NEW);
  if !runtime.contains(COMPILED_HOOK_NEW) {
    panic!("gen-rs: compiled_interact_call hook not found in hvm.rs");
  }
  runtime.push_str(WRAPPERS);
  runtime.push('\n');
  runtime.push_str(&cmp::compile_book(cmp::Target::Rust, book));
  runtime.push('\n');

  let mut names = String::new();
  names.push_str("  let book = Book { defs: vec![\n");
  for def in &book.defs {
    names.push_str(&format!(
      "    Def {{ name: {}.to_string(), safe: {}, root: Port(0), rbag: vec![], node: vec![], vars: 0 }},\n",
      rust_str(&def.name),
      def.safe
    ));
  }
  names.push_str("  ]};\n");

  let baked_tpc = hvm::default_tpc(num_cpus::get_physical());
  let max_tpc = hvm::MAX_TPC;

  format!(
    r#"// Generated by hvm gen-rs.
// rustc --edition 2021 -C opt-level=3 -C lto=thin -C codegen-units=1 -C target-cpu=native file.rs
#![allow(dead_code, unused_imports, unused_variables, unused_mut, unused_assignments, unused_parens, non_snake_case)]

mod hvm {{
{runtime}
}}

mod ast {{
{readback}
}}

fn main() {{
  use hvm::*;
  {names}
  let threads = default_threads();
  let net = if threads > 1 {{
    GNet::with_workers(heap_len(), heap_len(), threads)
  }} else {{
    GNet::new(heap_len(), heap_len())
  }};
  let main_id = book.defs.iter().position(|def| def.name == "main").expect("missing @main");
  let boot = Pair::new(Port::new(REF, main_id as u32), ROOT);
  net.vars_create(ROOT.get_val() as usize, NONE);
  let start = std::time::Instant::now();
  if threads <= 1 {{
    let mut tm = TMem::new(0, 1);
    tm.push_redex(&net, boot);
    tm.evaluator(&net, &book);
  }} else {{
    TMem::evaluator_pool(&net, &book, boot, threads);
  }}
  let duration = start.elapsed();
  if let Some(tree) = ast::Net::readback(&net, &book) {{
    println!("Result: {{}}", tree.show());
  }} else {{
    println!("Readback failed. Printing GNet memdump...\n");
    println!("{{}}", net.show());
  }}
  let itrs = net.itrs.load(std::sync::atomic::Ordering::Relaxed);
  println!("- ITRS: {{}}", itrs);
  println!("- TIME: {{:.2}}s", duration.as_secs_f64());
  println!("- MIPS: {{:.2}}", itrs as f64 / duration.as_secs_f64().max(1e-9) / 1_000_000.0);
}}

fn default_threads() -> u32 {{
  if let Ok(v) = std::env::var("HVM_THREADS") {{
    if let Ok(n) = v.parse::<u32>() {{
      return n.max(1).min({max_tpc});
    }}
  }}
  {baked_tpc}
}}
"#,
    runtime = runtime,
    readback = READBACK_RS,
    names = names,
    baked_tpc = baked_tpc,
    max_tpc = max_tpc,
  )
}

fn rust_str(s: &str) -> String {
  format!("{s:?}")
}
