name: windows
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build (MSVC link.exe)
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
            call "%%i\VC\Auxiliary\Build\vcvars64.bat"
          )
          set RUSTFLAGS=-C linker=link.exe
          cargo build --release
      - name: Rust interpreter smoke
        shell: cmd
        run: |
          target\release\hvm.exe run tests\programs\hello-world.hvm
      - name: Test
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
            call "%%i\VC\Auxiliary\Build\vcvars64.bat"
          )
          set RUSTFLAGS=-C linker=link.exe
          cargo test --release -- --skip test_run_examples
